using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Design;
using Microsoft.Extensions.Logging;
using TesterBase.DataContext;

namespace LocalDatabase.Setup
{
    public class DynamicConnectionDbFactory : IDesignTimeDbContextFactory<SqlQueryBuilderTestDataContext>
    {
        public SqlQueryBuilderTestDataContext CreateDbContext(string[] args)
        {
            var loggerFactory = new LoggerFactory();
            var options = new DbContextOptionsBuilder<SqlQueryBuilderTestDataContext>()
            .UseSqlServer(Constants.AlessaConnectionString)
            .UseLoggerFactory(loggerFactory) //Optional, this logs SQL generated by EF Core to the Console
            .Options;

            return new SqlQueryBuilderTestDataContext(options);
        }
    }
}
